OPENAI_API_KEY = "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"
AMADEUS_CLIENT_ID = "nX5GJYE9ph5XLFi42v1FxLKFgKl9kEtG"
AMADEUS_CLIENT_SECRET = "G29DPlJWhThhxEHG"
